### ISSUE TITLE
data.forEach in actor diagram

### ISSUE THREAD

**Issue by CountNick** [TheKevSter35/web-app-from-scratch-1920#11]
I noticed something in your actordigram: 

In the render module there is a function called RENDER_OVERVIEW(). However the Data module also has a function named DATA_FOREACH() which seems from the looks of your code to also be responsible for rendering the HTML. You might want to put that in the render function

https://github.com/TheKevSter35/web-app-from-scratch-1920/blob/d3176d6762139b5d5e81af57da44d2f6cb23e1e2/js/script.js#L34-L84

**Comment by TheKevSter35** [comment]
actordiagram is updated
