### ISSUE TITLE
Add a description to your diagrams.

### ISSUE THREAD

**Issue by jenniferslagt** [TheKevSter35/web-app-from-scratch-1920#15]
What is an actor diagram? What is an interactive diagram? ![bitmoji](https://render.bitstrips.com/v2/cpanel/1c5d22d0-3cc8-43e5-a8bd-a9f65e19c64f-83c93cc0-d0ae-4742-a59b-b1a0ec5de8e6-v1.png?transparent=1&palette=1&width=246)

**Comment by TheKevSter35** [comment]
description are added
