### ISSUE TITLE
Be consistent with writing your functions

### ISSUE THREAD

**Issue by jenniferslagt** [TheKevSter35/web-app-from-scratch-1920#16]
Sometimes you use an arrow function and sometimes you don't.![bitmoji](https://render.bitstrips.com/v2/cpanel/fbf70eb2-c012-465e-9c1e-7b092675dfd8-83c93cc0-d0ae-4742-a59b-b1a0ec5de8e6-v1.png?transparent=1&palette=1&width=246)

**Comment by TheKevSter35** [comment]
is solved by adding module

(cool img : D )
