### ISSUE TITLE
XMLhttprequest

### ISSUE THREAD

**Issue by CountNick** [TheKevSter35/web-app-from-scratch-1920#9]
I noticed you are fetching data with the a XMLHttpRequest, you might want to change this into a promise. You can do ths with the fetch api: 
* [fetch mdn](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) 
* Another example: [Use fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)

https://github.com/TheKevSter35/web-app-from-scratch-1920/blob/d3176d6762139b5d5e81af57da44d2f6cb23e1e2/js/script.js#L18-L23

**Comment by TheKevSter35** [comment]
with the tutorial from [studio ghibli api ](https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/) they used XMLHttpRequest. Fetch doesn't work i tried : (
